language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.9
  - DJANGO=1.10

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U setuptools
  - pip install Django==$DJANGO
  - # pip install coveralls
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests, e.g. python setup.py test
script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - # coverage run --source=lino setup.py test
  - inv prep test

after_success:
  # coveralls

notifications:
  email:
    recipients:
        #tonis.piip@gmail.com
        - secure: K86wAaWqn9JW9uwaMfM6A1XMVY3aiz7+9PiFLJLH8QbQSHlSxvRpLtUzB6COZnyLSDbmbpXaMZfccL7Rz3YntjnOE8FEP2g453rL97suF58sUxqgNm40FNth++RgZNsIDDkHjovwbknVPVt2OXvgI6lHX+rA52Icgka1oe4I/is=
        #luc.saffre@gmail.com
        - secure: PI5TM+LEssN/WbnMmRylCnEkhmME/VmyKcFik25cZvnfKQcqp9gHTZ6xCVSFbPFF12u+RCohqs/joA7xMaBlVVmCwU8NNubw75xO8apLoaCcAAOMy/mRLDIpNDzRELt+LLp7HNyjvOT8nf1xmTfrbX/44ImJjHfIdgT6UPGhr+o=
